server:
  host: 0.0.0.0
  port: 8080
  mode: debug
log:
  filename: /tmp/log.txt
  max_size: 10
  max_backups: 10
  max_age: 7
  compress: true
db:
  dsn: postgres://user:pass@127.0.0.1:5432/db?sslmode=disable
  # dsn: root:12345@tcp(127.0.0.1:3306)/db?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: 127.0.0.1:6479
  password:
  db: 0